<html>
<head>
	<title><?=$TITLE?></title>
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1251"/>
	<meta http-equiv="Content-language" content ="ru">
	<meta name="robots" content="all" />
	<meta name="author" content="Gleb Pereyaslavskiy" />
	<meta name="copyright" content="Copyright 2007 Gleb Pereyaslavskiy" />
	<meta name="distribution" content="global" />
	<link rel="stylesheet" href="http://susek.ru/design/css/style.css" type="text/css">
	<?=$HEAD?>
</head>
<body>
<div id="cpl">
<font size="-1">
<a class="perm" href="http://susek.ru/screbi">Скреби</a> | <a class="perm" href="http://susek.ru/nabey">набивай</a> | <a class="perm" href="http://susek.ru/blog">будь в курсе</a> | <a class="perm" href="http://susek.ru/guestblog">выскажись</a></font>
</div>
<br clear="all" />
<?=$BODY?>
<!--page generated at <?=$PAGE_AT_TIME?> in <?=$PAGE_IN_TIME?>-->
</body></html>